-- C/C++ language orchestration: clangd server config, buffer keymaps,
-- format-on-save with .clang-format detection, inlay hints, switch header/source,
-- and CMake/neotest/dap wiring helpers.
--
-- Public entrypoints:
--   require("lang.cpp").setup()                         -- one-shot startup setup
--   require("lang.cpp").setup_cmake_keymaps()           -- called from cmake-tools config
--   require("lang.cpp").setup_dap()                     -- called from dap config
--   require("lang.cpp").register_neotest_adapters()     -- returns adapter list

local M = {}

M.filetypes = { "c", "cpp", "objc", "objcpp", "cuda" }

M.format_patterns = {
  "*.c", "*.cc", "*.cpp", "*.cxx", "*.c++",
  "*.h", "*.hh", "*.hpp", "*.hxx", "*.h++",
  "*.m", "*.mm", "*.cu",
}

-- Resolve LLVM tooling paths; fall back to system binaries.
local function llvm_or_system(name)
  local llvm = "/opt/homebrew/opt/llvm/bin/" .. name
  if vim.fn.executable(llvm) == 1 then return llvm end
  return name
end

function M.clangd_path()   return llvm_or_system("clangd") end
function M.clang_format()  return llvm_or_system("clang-format") end
function M.clang_tidy()    return llvm_or_system("clang-tidy") end

-- Build clangd capabilities. Pulls cmp_nvim_lsp if present.
-- snippetSupport=true so clangd returns function signatures with placeholders
-- ($1, $2, …) for cursor jumps; luasnip handles expansion via nvim-cmp.
local function clangd_capabilities()
  local caps
  local ok, cmp_lsp = pcall(require, "cmp_nvim_lsp")
  if ok then
    caps = cmp_lsp.default_capabilities()
  else
    caps = vim.lsp.protocol.make_client_capabilities()
  end
  caps.textDocument.completion.completionItem.snippetSupport = true
  caps.textDocument.completion.completionItem.resolveSupport = {
    properties = { "documentation", "detail", "additionalTextEdits" },
  }
  caps.offsetEncoding = { "utf-16" }
  caps.textDocument.semanticTokens = {
    dynamicRegistration = false,
    requests = { range = false, full = { delta = true } },
    tokenTypes = {
      "namespace", "type", "class", "enum", "interface",
      "struct", "typeParameter", "parameter", "variable",
      "property", "enumMember", "event", "function", "method",
      "macro", "keyword", "modifier", "comment", "string",
      "number", "regexp", "operator", "decorator",
    },
    tokenModifiers = {
      "declaration", "definition", "readonly", "static",
      "deprecated", "abstract", "async", "modification",
      "documentation", "defaultLibrary",
    },
    formats = { "relative" },
    overlappingTokenSupport = true,
    multilineTokenSupport = true,
  }
  return caps
end

-- User-level fallback .clangd config for standalone files outside CMake/compile_commands.json.
-- Project-local .clangd or compile_commands.json take precedence over this file.
local function ensure_user_clangd_config()
  local cfg_dir = vim.fn.expand("~/.config/clangd")
  local cfg_file = cfg_dir .. "/config.yaml"
  if vim.fn.filereadable(cfg_file) == 1 then return end
  vim.fn.mkdir(cfg_dir, "p")
  local content = table.concat({
    "# User-level clangd defaults — applied to files outside any project.",
    "# Generated by lua/lang/cpp.lua. Edit freely; this file is not regenerated.",
    "CompileFlags:",
    "  Add:",
    "    - -std=c++20",
    "    - -Wall",
    "    - -Wextra",
    "  Compiler: clang++",
    "Diagnostics:",
    "  UnusedIncludes: Strict",
    "  MissingIncludes: Strict",
    "",
  }, "\n")
  local f = io.open(cfg_file, "w")
  if f then
    f:write(content)
    f:close()
  end
end

function M.setup_server()
  ensure_user_clangd_config()

  vim.lsp.config("clangd", {
    cmd = {
      M.clangd_path(),
      "--background-index",
      "--clang-tidy",
      "--completion-style=detailed",
      "--function-arg-placeholders=true",
      "--header-insertion=iwyu",
      "--header-insertion-decorators",
      "--fallback-style=LLVM",
      "--all-scopes-completion",
      "--pch-storage=memory",
      "--cross-file-rename",
      "--enable-config",
      "--limit-results=100",
      "-j=4",
    },
    capabilities = clangd_capabilities(),
    init_options = {
      usePlaceholders = true,
      completeUnimported = true,
      clangdFileStatus = true,
    },
  })
  vim.lsp.enable("clangd")
end

-- ─────────────────────────────────────────────────────────────────────────────
-- Format-on-save state
-- ─────────────────────────────────────────────────────────────────────────────
-- Per-buffer override: vim.b[buf].cpp_format_on_save
--   nil   → auto: enabled iff .clang-format reachable upward from the file
--   true  → forced on
--   false → forced off

local function find_upward(name, from)
  local found = vim.fs.find(name, { upward = true, path = from, type = "file" })
  return found and found[1] or nil
end

local function has_clang_format(bufnr)
  local fname = vim.api.nvim_buf_get_name(bufnr or 0)
  if fname == "" then return false end
  return find_upward(".clang-format", vim.fs.dirname(fname)) ~= nil
end

function M.should_format_on_save(bufnr)
  bufnr = bufnr or 0
  local override = vim.b[bufnr].cpp_format_on_save
  if override ~= nil then return override end
  return has_clang_format(bufnr)
end

function M.toggle_format_on_save(bufnr)
  bufnr = bufnr or 0
  local effective = M.should_format_on_save(bufnr)
  vim.b[bufnr].cpp_format_on_save = not effective
  vim.notify(
    ("clang-format on save: %s%s"):format(
      vim.b[bufnr].cpp_format_on_save and "ON" or "OFF",
      has_clang_format(bufnr) and "" or " (no .clang-format found)"
    ),
    vim.log.levels.INFO
  )
end

-- ─────────────────────────────────────────────────────────────────────────────
-- Buffer actions
-- ─────────────────────────────────────────────────────────────────────────────

local function switch_source_header(bufnr)
  local clients = vim.lsp.get_clients({ bufnr = bufnr, name = "clangd" })
  if #clients == 0 then
    vim.notify("clangd not attached", vim.log.levels.WARN)
    return
  end
  local params = { uri = vim.uri_from_bufnr(bufnr) }
  clients[1]:request("textDocument/switchSourceHeader", params, function(err, result)
    if err then
      vim.notify("switchSourceHeader: " .. err.message, vim.log.levels.WARN)
      return
    end
    if not result then
      vim.notify("No matching source/header file", vim.log.levels.INFO)
      return
    end
    vim.cmd.edit(vim.uri_to_fname(result))
  end, bufnr)
end

local function toggle_inlay_hints(bufnr)
  if not (vim.lsp.inlay_hint and vim.lsp.inlay_hint.enable) then
    vim.notify("Inlay hints not supported in this Neovim version", vim.log.levels.WARN)
    return
  end
  local enabled = vim.lsp.inlay_hint.is_enabled({ bufnr = bufnr })
  vim.lsp.inlay_hint.enable(not enabled, { bufnr = bufnr })
  vim.notify(("Inlay hints: %s"):format((not enabled) and "ON" or "OFF"), vim.log.levels.INFO)
end

local function format_buffer(bufnr)
  local ok, conform = pcall(require, "conform")
  if not ok then
    vim.notify("conform.nvim not loaded", vim.log.levels.ERROR)
    return
  end
  conform.format({ bufnr = bufnr, async = false, timeout_ms = 3000, lsp_format = "never" })
end

-- ─────────────────────────────────────────────────────────────────────────────
-- Type hierarchy (parents/children) with treesitter-driven auto-detect of the
-- enclosing class/struct/union and a Telescope picker for multi-result UX.
-- ─────────────────────────────────────────────────────────────────────────────

local CLASS_NODES = {
  class_specifier  = true,
  struct_specifier = true,
  union_specifier  = true,
}

local function enclosing_class_specifier(bufnr)
  local ok, parser = pcall(vim.treesitter.get_parser, bufnr)
  if not ok or not parser then return nil end
  local tree = parser:parse()[1]
  if not tree then return nil end

  local cur = vim.api.nvim_win_get_cursor(0)
  local row, col = cur[1] - 1, cur[2]
  local node = tree:root():named_descendant_for_range(row, col, row, col)
  while node do
    if CLASS_NODES[node:type()] then return node end
    node = node:parent()
  end
  return nil
end

local function enclosing_class_node(bufnr)
  local class = enclosing_class_specifier(bufnr)
  if not class then return nil end
  local name_field = class:field("name")
  return name_field and name_field[1] or nil
end

-- Convert a treesitter node's start to an LSP position respecting the client's
-- offset encoding (clangd uses utf-16; see clangd_capabilities above).
local function ts_node_to_lsp_position(bufnr, node, encoding)
  local row, byte_col = node:start()
  local line = vim.api.nvim_buf_get_lines(bufnr, row, row + 1, false)[1] or ""
  local character = byte_col
  if encoding == "utf-16" or encoding == "utf-32" then
    local ok, idx = pcall(vim.str_utfindex, line, encoding, byte_col)
    if ok then character = idx end
  end
  return { line = row, character = character }
end

local function jump_to_lsp_item(item)
  vim.cmd.edit(vim.uri_to_fname(item.uri))
  local pos = item.selectionRange and item.selectionRange.start or item.range.start
  vim.api.nvim_win_set_cursor(0, { pos.line + 1, pos.character })
  vim.cmd("normal! zz")
end

local function show_hierarchy_picker(items, title)
  local ok_pickers,   pickers   = pcall(require, "telescope.pickers")
  local ok_finders,   finders   = pcall(require, "telescope.finders")
  local ok_conf,      conf      = pcall(require, "telescope.config")
  local ok_actions,   actions   = pcall(require, "telescope.actions")
  local ok_state,     state     = pcall(require, "telescope.actions.state")
  if not (ok_pickers and ok_finders and ok_conf and ok_actions and ok_state) then
    vim.notify("Telescope not available", vim.log.levels.ERROR)
    return
  end

  pickers.new({}, {
    prompt_title = title,
    finder = finders.new_table({
      results = items,
      entry_maker = function(item)
        local fname = vim.uri_to_fname(item.uri)
        local pos = item.selectionRange and item.selectionRange.start or item.range.start
        local relpath = vim.fn.fnamemodify(fname, ":.")
        return {
          value    = item,
          display  = string.format("%s  %s:%d", item.name, relpath, pos.line + 1),
          ordinal  = item.name .. " " .. relpath,
          filename = fname,
          lnum     = pos.line + 1,
          col      = pos.character + 1,
        }
      end,
    }),
    sorter   = conf.values.generic_sorter({}),
    previewer = conf.values.grep_previewer({}),
    attach_mappings = function(prompt_bufnr, _)
      actions.select_default:replace(function()
        local entry = state.get_selected_entry()
        actions.close(prompt_bufnr)
        if entry and entry.value then
          jump_to_lsp_item(entry.value)
        end
      end)
      return true
    end,
  }):find()
end

local function run_type_hierarchy(bufnr, direction)
  local clients = vim.lsp.get_clients({ bufnr = bufnr, name = "clangd" })
  if #clients == 0 then
    vim.notify("clangd not attached", vim.log.levels.WARN)
    return
  end
  local client = clients[1]

  local name_node = enclosing_class_node(bufnr)
  if not name_node then return end  -- silent: cursor outside any class/struct/union

  local params = {
    textDocument = { uri = vim.uri_from_bufnr(bufnr) },
    position     = ts_node_to_lsp_position(bufnr, name_node, client.offset_encoding),
  }

  client:request("textDocument/prepareTypeHierarchy", params, function(err, items)
    if err then
      vim.notify("prepareTypeHierarchy: " .. err.message, vim.log.levels.WARN)
      return
    end
    if not items or #items == 0 then
      vim.notify("No type hierarchy at cursor", vim.log.levels.INFO)
      return
    end

    local method = "typeHierarchy/" .. direction
    local pending = #items
    local seen, collected = {}, {}

    for _, item in ipairs(items) do
      client:request(method, { item = item }, function(err2, result)
        pending = pending - 1
        if not err2 and result then
          for _, r in ipairs(result) do
            local pos = r.selectionRange and r.selectionRange.start or r.range.start
            local key = r.uri .. ":" .. pos.line .. ":" .. pos.character
            if not seen[key] then
              seen[key] = true
              collected[#collected + 1] = r
            end
          end
        end
        if pending == 0 then
          if #collected == 0 then
            vim.notify(("No %s"):format(direction), vim.log.levels.INFO)
          elseif #collected == 1 then
            jump_to_lsp_item(collected[1])
          else
            local title = (direction == "supertypes") and "Supertypes (parents)" or "Subtypes (children)"
            show_hierarchy_picker(collected, title)
          end
        end
      end, bufnr)
    end
  end, bufnr)
end

-- ─────────────────────────────────────────────────────────────────────────────
-- LspAttach handler — buffer-local keymaps for clangd buffers
-- ─────────────────────────────────────────────────────────────────────────────

local function map(bufnr, mode, lhs, rhs, desc)
  vim.keymap.set(mode, lhs, rhs, { buffer = bufnr, silent = true, desc = desc })
end

-- Buffer-local signature help via ray-x/lsp_signature.nvim.
-- Scoped to clangd buffers so other languages stay untouched.
local function setup_signature_help(client, bufnr)
  local ok, sig = pcall(require, "lsp_signature")
  if not ok then return end
  sig.on_attach({
    bind = true,
    hint_enable = false,        -- no inline virtual hints; only floating popup
    floating_window = true,
    floating_window_above_cur_line = true,
    hi_parameter = "IncSearch",
    handler_opts = { border = "rounded" },
    toggle_key = "<C-s>",       -- toggle signature window
    select_signature_key = "<C-n>",
  }, bufnr)
end

local function on_clangd_attach(client, bufnr)
  -- Header/source switch.
  map(bufnr, "n", "gh", function() switch_source_header(bufnr) end, "C++: switch source/header")
  map(bufnr, "n", "<F4>", function() switch_source_header(bufnr) end, "C++: switch source/header")

  -- Signature help popup.
  setup_signature_help(client, bufnr)

  -- Hierarchies.
  map(bufnr, "n", "<leader>ch", vim.lsp.buf.incoming_calls,  "C++: incoming calls")
  map(bufnr, "n", "<leader>cH", vim.lsp.buf.outgoing_calls,  "C++: outgoing calls")
  map(bufnr, "n", "<leader>ct", function() run_type_hierarchy(bufnr, "subtypes") end,
    "C++: subtypes (children)")
  map(bufnr, "n", "<leader>cT", function() run_type_hierarchy(bufnr, "supertypes") end,
    "C++: supertypes (parents)")

  -- Inlay hints — OFF by default per spec.
  if vim.lsp.inlay_hint then
    vim.lsp.inlay_hint.enable(false, { bufnr = bufnr })
  end
  map(bufnr, "n", "<leader>ci", function() toggle_inlay_hints(bufnr) end, "C++: toggle inlay hints")

  -- Formatting.
  map(bufnr, "n", "<leader>cf", function() format_buffer(bufnr) end,           "C++: format buffer")
  map(bufnr, "x", "<leader>cf", function() format_buffer(bufnr) end,           "C++: format selection")
  map(bufnr, "n", "<leader>cF", function() M.toggle_format_on_save(bufnr) end, "C++: toggle format-on-save")

  -- clangd_extensions commands.
  map(bufnr, "n", "<leader>cs", "<cmd>ClangdSymbolInfo<cr>",  "C++: symbol info")
  map(bufnr, "n", "<leader>cm", "<cmd>ClangdMemoryUsage<cr>", "C++: clangd memory usage")
  map(bufnr, "n", "<leader>cA", "<cmd>ClangdAST<cr>",         "C++: clangd AST")

  -- Neotest (buffer-local so we don't pollute other languages globally).
  local ok_neotest, neotest = pcall(require, "neotest")
  if ok_neotest then
    map(bufnr, "n", "<leader>tt", function() neotest.run.run() end,                             "C++: test nearest")
    map(bufnr, "n", "<leader>tf", function() neotest.run.run(vim.fn.expand("%")) end,           "C++: test file")
    map(bufnr, "n", "<leader>tT", function() neotest.run.run(vim.fn.getcwd()) end,              "C++: test all")
    map(bufnr, "n", "<leader>td", function() neotest.run.run({ strategy = "dap" }) end,         "C++: debug nearest test")
    map(bufnr, "n", "<leader>ts", function() neotest.summary.toggle() end,                      "C++: test summary")
    map(bufnr, "n", "<leader>to", function() neotest.output.open({ enter = true }) end,         "C++: test output")
    map(bufnr, "n", "<leader>tx", function() neotest.run.stop() end,                            "C++: stop test")
  end
end

function M.setup_autocmds()
  local group = vim.api.nvim_create_augroup("CppLang", { clear = true })

  vim.api.nvim_create_autocmd("LspAttach", {
    group = group,
    callback = function(args)
      local client = vim.lsp.get_client_by_id(args.data.client_id)
      if not client or client.name ~= "clangd" then return end
      on_clangd_attach(client, args.buf)
    end,
  })

  vim.api.nvim_create_autocmd("BufWritePre", {
    group = group,
    pattern = M.format_patterns,
    callback = function(args)
      if not M.should_format_on_save(args.buf) then return end
      local ok, conform = pcall(require, "conform")
      if not ok then return end
      conform.format({ bufnr = args.buf, async = false, timeout_ms = 3000, lsp_format = "never" })
    end,
  })

  -- Register dap configurations the first time a C/C++ file is opened.
  -- nvim-dap is owned by lua/plugins/debug.lua; we only inject configs.
  local dap_registered = false
  vim.api.nvim_create_autocmd("FileType", {
    group = group,
    pattern = { "c", "cpp" },
    callback = function()
      if dap_registered then return end
      dap_registered = true
      M.setup_dap()
    end,
  })
end

-- ─────────────────────────────────────────────────────────────────────────────
-- CMake keymaps (called from cmake-tools.nvim config)
-- ─────────────────────────────────────────────────────────────────────────────

function M.setup_cmake_keymaps()
  local m = function(lhs, rhs, desc)
    vim.keymap.set("n", lhs, rhs, { silent = true, desc = desc })
  end
  m("<leader>mg", "<cmd>CMakeGenerate<cr>",            "CMake: generate (configure)")
  m("<leader>mb", "<cmd>CMakeBuild<cr>",               "CMake: build")
  m("<leader>mr", "<cmd>CMakeRun<cr>",                 "CMake: run")
  m("<leader>md", "<cmd>CMakeDebug<cr>",               "CMake: debug")
  m("<leader>mt", "<cmd>CMakeSelectLaunchTarget<cr>",  "CMake: select launch target")
  m("<leader>mT", "<cmd>CMakeSelectBuildTarget<cr>",   "CMake: select build target")
  m("<leader>mB", "<cmd>CMakeSelectBuildType<cr>",     "CMake: select build type")
  m("<leader>mk", "<cmd>CMakeSelectKit<cr>",           "CMake: select kit")
  m("<leader>mq", "<cmd>CMakeQuickBuild<cr>",          "CMake: quick build")
  m("<leader>mc", "<cmd>CMakeClean<cr>",               "CMake: clean")
  m("<leader>mx", "<cmd>CMakeStop<cr>",                "CMake: stop running task")
end

-- ─────────────────────────────────────────────────────────────────────────────
-- DAP configuration for C/C++ — uses cmake-tools launch target when available,
-- otherwise prompts for executable path. Called from dap setup.
-- ─────────────────────────────────────────────────────────────────────────────

function M.setup_dap()
  local ok, dap = pcall(require, "dap")
  if not ok then return end

  local function pick_executable()
    local ok_cmake, cmake = pcall(require, "cmake-tools")
    if ok_cmake then
      local target_path = cmake.get_launch_target_path and cmake.get_launch_target_path()
      if target_path and target_path ~= "" and vim.fn.executable(target_path) == 1 then
        return target_path
      end
    end
    return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
  end

  local function parse_args()
    local raw = vim.fn.input("Program arguments (space-separated): ")
    if raw == "" then return {} end
    return vim.split(raw, "%s+")
  end

  local cpp_config = {
    {
      name = "Launch (codelldb, cmake target)",
      type = "codelldb",
      request = "launch",
      program = pick_executable,
      args = parse_args,
      cwd = "${workspaceFolder}",
      stopOnEntry = false,
      console = "integratedTerminal",
    },
    {
      name = "Attach to process (codelldb)",
      type = "codelldb",
      request = "attach",
      pid = function() return require("dap.utils").pick_process() end,
      cwd = "${workspaceFolder}",
    },
  }

  dap.configurations.cpp = cpp_config
  dap.configurations.c = cpp_config
end

-- ─────────────────────────────────────────────────────────────────────────────
-- Neotest adapters — extensible list. Add adapters by editing this function.
-- ─────────────────────────────────────────────────────────────────────────────

function M.neotest_adapters()
  local adapters = {}

  local ok_vimtest, vim_test = pcall(require, "neotest-vim-test")
  if ok_vimtest then
    -- Default vim-test C/C++ runner. Catch2 is the user's primary framework;
    -- override per project via :let g:test#cpp#runner = '...' or .vim-test config.
    vim.g["test#cpp#runner"] = vim.g["test#cpp#runner"] or "catch2"
    vim.g["test#c#runner"]   = vim.g["test#c#runner"]   or "catch2"

    table.insert(adapters, vim_test({
      -- Neotest uses neotest-vim-test only for filetypes other adapters don't cover.
      ignore_file_types = { "python", "lua", "rust", "go", "java", "javascript", "typescript" },
    }))
  end

  return adapters
end

-- ─────────────────────────────────────────────────────────────────────────────
-- cmp source list for C/C++. Includes treesitter so keywords (private, public,
-- noexcept, constexpr, …) and project identifiers come through even when
-- clangd doesn't propose them in the current context.
--
-- Other languages keep the global cmp config from lua/plugins/completions.lua.
-- ─────────────────────────────────────────────────────────────────────────────

function M.setup_cmp_filetypes()
  local ok, cmp = pcall(require, "cmp")
  if not ok then return end

  local sources_top = {
    -- Filter out clangd's `Snippet` items (kind 15) — luasnip handles snippets.
    { name = "nvim_lsp", priority = 1000,
      entry_filter = function(entry) return entry:get_kind() ~= 15 end },
    { name = "luasnip",    priority = 800 },
    { name = "treesitter", priority = 600, keyword_length = 1 },
    { name = "path",       priority = 500 },
  }
  local sources_fallback = {
    { name = "buffer", priority = 250, keyword_length = 2 },
  }

  for _, ft in ipairs({ "c", "cpp", "objc", "objcpp", "cuda" }) do
    cmp.setup.filetype(ft, {
      sources = cmp.config.sources(sources_top, sources_fallback),
    })
  end
end

-- ─────────────────────────────────────────────────────────────────────────────
-- Public setup
-- ─────────────────────────────────────────────────────────────────────────────

function M.setup()
  M.setup_server()
  M.setup_autocmds()

  -- cmp.setup.filetype is global, so it's safe to call once at startup
  -- (nvim-cmp from completions.lua loads eagerly).
  vim.api.nvim_create_autocmd("VimEnter", {
    once = true,
    callback = function() M.setup_cmp_filetypes() end,
  })
end

return M
